export default [
    {
        id: '2332sdfsdgdf',
        authorName: 'Abdelfattah',
        authorImage: 'https://placehold.co/600x400',
        itemImage: 'https://placehold.co/600x400',
        itemName: 'Iphone 12 pro max',
        price: 5000,
        currency: 'AED',
        likesNumber: 28,
        commentsNumber: 12,
        itemDescription: 'This is iphone 12 pro max',
        tags: ['iphones', 'mobile phones', 'cases', 'electronics'],
        isFavourite: false,
    },
    {
        id: 'afsgdgf235453',
        authorName: 'Omar',
        authorImage: 'https://placehold.co/600x400',
        itemImage: 'https://placehold.co/600x400',
        itemName: 'Samsung 20 Ultra',
        price: 3000,
        currency: 'AED',
        likesNumber: 12,
        commentsNumber: 3,
        itemDescription: 'This is Samsung 20 ultra',
        tags: ['iphones', 'mobile phones', 'cases', 'electronics'],
        isFavourite: true,
    },
    {
        id: 'sgdfgdffh43464',
        authorName: 'Moawad',
        authorImage: 'https://placehold.co/600x400',
        itemImage: 'https://placehold.co/600x400',
        itemName: 'Xiaomi Note 10 Pro',
        price: 1000,
        currency: 'AED',
        likesNumber: 1,
        commentsNumber: 1,
        itemDescription: 'This Xiaomi Note 10 Pro',
        tags: ['iphones', 'mobile phones', 'cases', 'electronics'],
        isFavourite: true,
    },
]